server:
  port: 8888

spring:
  application:
    name: springMovie

  redis:
    host: localhost
    port: 6379
    database: 0

  datasource:
    url: jdbc:mysql://142.171.9.183:6060/movie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  # model
  type-aliases-package: com.springMovie.domain
  # xml file
  mapper-locations: classpath:mapper/*.xml